#!/usr/bin/env bash
# fix_paths.sh – move CSVs generated by export_local_db.sh to the location expected by compare_datasets.py

# Resolve source directory (where export_local_db.sh placed the CSVs)
SRC_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/../app/scripts/local_export" && pwd)
# Resolve destination directory (project root/local_export)
DST_DIR="$(pwd)/local_export"

mkdir -p "$DST_DIR"

# Copy CSV files (if they exist)
if [[ -f "$SRC_DIR/local_houses.csv" ]]; then
  cp "$SRC_DIR/local_houses.csv" "$DST_DIR/"
fi
if [[ -f "$SRC_DIR/local_activities.csv" ]]; then
  cp "$SRC_DIR/local_activities.csv" "$DST_DIR/"
fi

echo "CSV files moved to $DST_DIR"
